[deps]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
PathStrings = "313e5630-e80e-42f4-9e3f-8bfd502c4f6a"

[sources]
PathStrings = {url = "https://github.com/wookay/PathStrings.jl", rev = "main"}

[compat]
PathStrings = "0.1"
